# Generated by Django 4.2.8 on 2023-12-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_tournament_player1_alter_tournament_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='losers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winners',
            field=models.IntegerField(default=0),
        ),
    ]
