# Generated by Django 4.2.8 on 2024-01-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_anonymous_mode'),
        ('index', '0004_tournament_losers_tournament_winner1_and_more'),
    ]

    operations = [
    ]
